### ISSUE TITLE
The ms-teams-notification step is executed by the workflow successfully, but MS Teams channel don't display any notifications

### ISSUE THREAD

**Issue by ramyaramdasan** [jdcargile/ms-teams-notification#11]
Hi, 

I have added the following code snippet to my yml file and the workflow executed successfully without any error. However, I don't get the notification on the MS Team Channel. Everything looks good with webhook and I used a github token which has been already in use in the same workflow. I am not sure what needs to be fixed, please help.
 steps:
      - name: Notify dedicated teams channel
        uses: jdcargile/ms-teams-notification@v1.3
        with:
          github-token: ${{ github.token }} # this will use the runner's token.
          ms-teams-webhook-uri: ${{ secrets.MSTEAMS_WEBHOOK }}
          notification-summary: Pipeline starts 
          notification-color: 17a2b8
          timezone: America/Denver

Thanks
Ramya

**Comment by dhamo-pk** [comment]
Are you using the right webhook URI @ramyaramdasan? I use the same format and it works perfectly

**Comment by ramyaramdasan** [comment]
Hi @dhamo-pk, 

thanks for checking. Though I'm not sure what has changed, it works now when I retried. 

Thanks
Ramya
