### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by BrandonHenson-KR** [jdcargile/ms-teams-notification#56]
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: jdcargile/ms-teams-notification@v1.3. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

Node 12 has been out of support since [April 2022](https://github.com/nodejs/Release/#end-of-life-releases), as a result we have started the deprecation process of Node 12 for GitHub Actions. We plan to migrate all actions to run on Node16 by Summer 2023. We will monitor the progress of the migration and listen to the community for how things are going before we define a final date.
To raise awareness of the upcoming change, we are adding a warning into workflows which contain Actions running on Node 12. This will come into effect starting on September 27th.

**Comment by roman-hosek-deltatre** [comment]
Following on from our warning in workflows using Node 12, we will start enforcing the use of Node16 rather than Node12 on the 14th of June.
https://github.blog/changelog/2023-05-04-github-actions-all-actions-will-run-on-node16-instead-of-node12/

**Comment by beerkeeper** [comment]
And as of today, Node16 is EOL due to end of support for OpenSSL 1.1.1: https://nodejs.org/en/blog/announcements/nodejs16-eol

**Comment by SeptBlast** [comment]
@roman-hosek-deltatre thanks for the updates, the node12 migration is been handled and pushed to node20. the updated repository can be consumed from here https://github.com/marketplace/actions/microsoft-teams-notification-v2

FYI @roman-hosek-deltatre @beerkeeper

**Comment by jdcargile** [comment]
@SeptBlast, @beerkeeper, @roman-hosek-deltatre, I've updated this project and it should work now.
